#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" ; pushd `pwd` > /dev/null ; cd $DIR
. ./utils
echo "Initial PayDay daemon config"
mkdir -p ~/PayDayWalletBackups
killall -9 pdd
wait_pdd_stops
if [[ -f ~/.PayDay/wallet.dat ]] 
then
 x=`mktemp ~/PayDayWalletBackups/pdwallet_bak.XXXXXXXX`
 cp ~/.PayDay/wallet.dat $x
 echo "we've found wallet and backed it to $x"
fi
rm -fr ~/.PayDay
mkdir -p ~/.PayDay
echo -en "rpcuser=PayDayrpc\nrpcpassword=" > ~/.PayDay/PayDay.conf && date +%s%N | md5sum | awk '{print $1}' | base64 |  sed 's/\=//g' >> ~/.PayDay/PayDay.conf
echo "server=1" >> ~/.PayDay/PayDay.conf
pdd -daemon
sleep 1
wait_pdd_starts

crontab -l  | grep -v pdd > /tmp/pdd.cron
echo "@reboot pdd -daemon ">> /tmp/pdd.cron
echo "*/2 * * * *  pdd -daemon ">> /tmp/pdd.cron
crontab /tmp/pdd.cron
rm -f /tmp/pdd.cron
popd > /dev/null

