#!/bin/bash


CURL=`which curl`

IP=$1
PORT=$2
URPC=$3
PRPC=$4

check_params()
{
if [[ $IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
	nIP=$IP
else
	read -p "Enter IP/Domain address: " nIP
	echo ""
fi

if [[ $PORT =~ ^[0-9]{3,6}$ ]]; then
	nPORT=$PORT
else
	read -p "Enter PORT: " nPORT
	echo ""
fi

if [[ $URPC =~ ^[a-zA-Z0-9]+$  ]]; then
	nURPC=$URPC
else
	read -p "Enter RPC user: " nURPC
	echo ""
fi

if [[ $PRPC =~ ^[a-zA-Z0-9]+$ ]]; then
	nPRPC=$PRPC
else
	read -s -p "Enter RPC password: " nPRPC
	echo ""
fi

}

if [ "$CURL" == "" ]; then
	echo "For working this script need installed cURL binaries"
	exit 0
fi

if [ $# -ne 4 ]; then
	echo "Missing parameters in command, enter it now"
fi

check_params

CMD_ADDRS=`$CURL -s --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getaddressesbyaccount", "params": [""] }' -H 'content-type: text/plain;' "http://$nURPC:$nPRPC@$nIP:$nPORT/" 2>&1`

ANSWER=`echo $CMD_ADDRS | grep -oe "[a-zA-Z0-9]*" 2>&1`

for addr in $ANSWER
do
	if [ `expr length $addr` -gt 30 ]; then
		BALANSES=`$CURL -s https://explorer.paydaycoin.io/address/$addr | grep -oe "</td><td>[0-9\.]*</td>" | grep -oe "[0-9\.]*" 2>&1`
		if [ "$BALANSES" == "" ]; then
			BALANSES=0
		fi
		RESULT=`$CURL -s --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "dumpprivkey", "params": ["'$addr'"] }' -H 'content-type: text/plain;' "http://$nURPC:$nPRPC@$nIP:$nPORT/" 2>&1`
		RESULT=`echo $RESULT | grep -oe "[a-zA-Z0-9]*"`
		for privkey in $RESULT
		do
			if [ `expr length $privkey` -gt 30 ]; then
				PKEY=$privkey
			fi
		done
		echo "$nIP\t$addr\t$PKEY\t$BALANSES"
	fi
done
exit 0
