#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" ; pushd `pwd` > /dev/null ; cd $DIR

sudo mkdir -p /usr/bin
sudo mkdir -p /usr/local/bin
sudo rm -f /usr/bin/pdd
sudo rm -f /usr/local/bin/pdd
cp ./PayDayd /usr/local/bin/pdd
ln -s /usr/local/bin/pdd /usr/bin/pdd

popd > /dev/null

